version: "3.8"
services:
  python:
    build:
      context: ../
      dockerfile: ./docker/python38/Dockerfile
    container_name: "instagram-follower-check"
    image: python:3.7
    tty: true
    dns:
      - "8.8.8.8"
